[2024-11-26T14:57:32.975+0000] {processor.py:186} INFO - Started process (PID=2576) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T14:57:32.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T14:57:32.977+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:57:32.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T14:57:32.995+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:57:32.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:57:32.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T14:57:33.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.047 seconds
[2024-11-26T14:58:03.164+0000] {processor.py:186} INFO - Started process (PID=2642) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T14:58:03.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T14:58:03.167+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:58:03.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T14:58:03.180+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:58:03.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:58:03.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T14:58:03.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.039 seconds
[2024-11-26T14:58:33.486+0000] {processor.py:186} INFO - Started process (PID=2708) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T14:58:33.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T14:58:33.488+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:58:33.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T14:58:33.499+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:58:33.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:58:33.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T14:58:33.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.039 seconds
[2024-11-26T14:59:03.774+0000] {processor.py:186} INFO - Started process (PID=2774) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T14:59:03.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T14:59:03.777+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:59:03.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T14:59:03.789+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:59:03.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:59:03.790+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T14:59:03.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.048 seconds
[2024-11-26T14:59:34.433+0000] {processor.py:186} INFO - Started process (PID=2840) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T14:59:34.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T14:59:34.436+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:59:34.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T14:59:34.451+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:59:34.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:59:34.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T14:59:34.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.463 seconds
[2024-11-26T15:00:05.250+0000] {processor.py:186} INFO - Started process (PID=2906) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:00:05.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:00:05.252+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:00:05.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:00:05.264+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:00:05.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:00:05.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:00:05.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.040 seconds
[2024-11-26T15:00:36.257+0000] {processor.py:186} INFO - Started process (PID=2972) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:00:36.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:00:36.259+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:00:36.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:00:36.269+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:00:36.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:00:36.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:00:36.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.036 seconds
[2024-11-26T15:01:06.618+0000] {processor.py:186} INFO - Started process (PID=3038) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:01:06.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:01:06.620+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:01:06.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:01:06.634+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:01:06.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:01:06.635+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:01:06.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.045 seconds
[2024-11-26T15:01:37.024+0000] {processor.py:186} INFO - Started process (PID=3103) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:01:37.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:01:37.028+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:01:37.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:01:37.067+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:01:37.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:01:37.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:01:37.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.072 seconds
[2024-11-26T15:02:07.433+0000] {processor.py:186} INFO - Started process (PID=3175) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:02:07.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:02:07.437+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:02:07.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:02:07.450+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:02:07.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:02:07.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:02:07.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.047 seconds
[2024-11-26T15:02:37.710+0000] {processor.py:186} INFO - Started process (PID=3241) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:02:37.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:02:37.712+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:02:37.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:02:37.727+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:02:37.724+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:02:37.728+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:02:37.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.054 seconds
[2024-11-26T15:02:49.884+0000] {processor.py:186} INFO - Started process (PID=3295) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:02:49.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:02:49.886+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:02:49.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:02:49.906+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:02:49.903+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:02:49.908+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:02:49.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.049 seconds
[2024-11-26T15:03:20.577+0000] {processor.py:186} INFO - Started process (PID=3361) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:03:20.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:03:20.586+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:03:20.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:03:20.612+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:03:20.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:03:20.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:03:20.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.078 seconds
[2024-11-26T15:03:50.895+0000] {processor.py:186} INFO - Started process (PID=3427) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:03:50.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:03:50.898+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:03:50.898+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:03:50.912+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:03:50.910+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:03:50.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:03:50.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.042 seconds
[2024-11-26T15:04:21.371+0000] {processor.py:186} INFO - Started process (PID=3493) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:04:21.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:04:21.373+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:04:21.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:04:21.386+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:04:21.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:04:21.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:04:21.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.041 seconds
[2024-11-26T15:04:51.493+0000] {processor.py:186} INFO - Started process (PID=3559) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:04:51.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:04:51.499+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:04:51.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:04:51.515+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:04:51.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:04:51.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:04:51.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.057 seconds
[2024-11-26T15:05:21.997+0000] {processor.py:186} INFO - Started process (PID=3625) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:05:21.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:05:22.000+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:05:21.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:05:22.018+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:05:22.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:05:22.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:05:22.046+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.057 seconds
[2024-11-26T15:05:52.615+0000] {processor.py:186} INFO - Started process (PID=3691) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:05:52.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:05:52.618+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:05:52.618+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:05:52.639+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:05:52.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:05:52.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:05:52.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.070 seconds
[2024-11-26T15:06:22.847+0000] {processor.py:186} INFO - Started process (PID=3757) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:06:22.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:06:22.849+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:06:22.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:06:22.863+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:06:22.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:06:22.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:06:22.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.043 seconds
[2024-11-26T15:06:53.280+0000] {processor.py:186} INFO - Started process (PID=3823) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:06:53.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:06:53.282+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:06:53.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:06:53.298+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:06:53.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:06:53.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:06:53.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.046 seconds
[2024-11-26T15:07:23.712+0000] {processor.py:186} INFO - Started process (PID=3889) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:07:23.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:07:23.715+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:07:23.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:07:23.730+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:07:23.727+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:07:23.732+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:07:23.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.047 seconds
[2024-11-26T15:07:53.987+0000] {processor.py:186} INFO - Started process (PID=3955) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:07:53.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:07:53.989+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:07:53.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:07:54.003+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:07:54.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:07:54.004+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:07:54.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.042 seconds
[2024-11-26T15:08:24.532+0000] {processor.py:186} INFO - Started process (PID=4021) to work on /opt/airflow/dags/test_firestore.py
[2024-11-26T15:08:24.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_firestore.py for tasks to queue
[2024-11-26T15:08:24.534+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:08:24.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:08:24.547+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:08:24.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_firestore.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_firestore.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:08:24.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_firestore.py
[2024-11-26T15:08:24.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_firestore.py took 0.040 seconds
